### ISSUE TITLE
Failed to resolve: com.github.mmin18.layoutcast:library:1.+

### ISSUE THREAD

**Issue by taosimple** [mmin18/LayoutCast#13]
build的时候提示：
Error:(127, 13) Failed to resolve: com.github.mmin18.layoutcast:library:1.+

是直接按你写的：
compile 'com.github.mmin18.layoutcast:library:1.+@aar'
来配置的build.gradle 文件的

另外repositories用的是jcenter：
repositories {
        jcenter()
    }

**Comment by mmin18** [comment]
可以参考eclipse的方式，直接下载lcast.jar
