### ISSUE TITLE
Question about when cast.sh shell script been execute?

### ISSUE THREAD

**Issue by Folyd** [mmin18/LayoutCast#14]
Hi,I am very interested in this project,and i wanna to contribute to LayoutCast. I have read the IDEA plugin and library source code, i didn't get it  when does [cast.sh](https://github.com/mmin18/LayoutCast/blob/master/library/cast.sh) get execute?

 Can you help me?Thanks,any comment is welcome! :)

**Comment by mmin18** [comment]
https://github.com/mmin18/LayoutCast/blob/master/ide/IDEAPlugin/src/com/github/mmin18/layoutcast/ide/CastAction.java#L82
