### ISSUE TITLE
Cannot run LayoutCast

### ISSUE THREAD

**Issue by Seidak** [mmin18/LayoutCast#32]
Hi,
I have done everything according to start up tutorial, but when I want to run LayoutCast I get this error:

![image](https://cloud.githubusercontent.com/assets/6642480/9356535/ad78207e-4681-11e5-90dd-8f1f829aaf24.png)

Can you help me?
Thanks

**Comment by anjovazquez** [comment]
Hi, 
Same problem here, I have installed Android Studio under Windows environment.
Thanks in advance

**Comment by vivekanandg** [comment]
![screen shot 2015-08-19 at 11 09 01 pm](https://cloud.githubusercontent.com/assets/988523/9364066/fd856536-46c7-11e5-9f8e-30ba39dc8baa.png)
I get this :(

**Comment by wangtianya** [comment]
@Seidak Put Python.exe into path first

**Comment by mmin18** [comment]
put python.exe into PATH.
And if you have a "Not a PNG file", recheck that png file, open that png and resave it.

**Comment by vivekanandg** [comment]
@mmin18 thanks, my png was screwing things up

**Comment by Seidak** [comment]
@wangtianya @mmin18 thanks, path solved it.
