### ISSUE TITLE
when i use butterknife,found too many errors!

### ISSUE THREAD

**Issue by dxiaogang** [mmin18/LayoutCast#5]
when i use butterknife,found too many errors!

**Comment by smajdalf** [comment]
I have the same problem. When i delete the ButterKnife.inject() everything works fine.

**Comment by renannery** [comment]
I've tried to implementing Layout Cast in a project with Android Annotations, but are pop up many error like ButterKnife

**Comment by feliu** [comment]
+1

**Comment by feliu** [comment]
I have problems with annotations too, @DebugLog of hugo, @Subscribe of eventbus...
